### ISSUE TITLE
In weka explorer, MultiSearch raises 'java.lang.NoClassDefFoundError'

### ISSUE THREAD

**Issue by krkhnh** [fracpete/multisearch-weka-package#3]
Weka version: `3.7.13`
multisearch version: `2015.9.2` (But displayed as `2014.12.10` in weka package manager. Maybe another issue?)

I set class attribute, but still raises error.

Error msg:

```
java.lang.NoClassDefFoundError: weka/core/MathematicalExpression
        weka.core.SetupGenerator.evaluate(SetupGenerator.java:380)
        weka.classifiers.meta.multisearch.DefaultEvaluationTask.doRun(DefaultEvaluationTask.java:68)
        weka.classifiers.meta.multisearch.AbstractEvaluationTask.run(AbstractEvaluationTask.java:88)
        java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        java.lang.Thread.run(Unknown Source)

        at weka.core.SetupGenerator.evaluate(SetupGenerator.java:380)
        at weka.classifiers.meta.multisearch.DefaultEvaluationTask.doRun(DefaultEvaluationTask.java:68)
        at weka.classifiers.meta.multisearch.AbstractEvaluationTask.run(AbstractEvaluationTask.java:88)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by fracpete** [comment]
Weka 3.7.13 had some significant changes under the hood since 3.7.12. The plugin has only been tested with Weka up to 3.7.12.

**Comment by krkhnh** [comment]
Thank you. I'll test in `3.7.12` if I can.

**Comment by krkhnh** [comment]
Works in `3.7.12`

**Comment by fracpete** [comment]
OK. Thanks for testing. Will see whether I can make a new release at some stage.

**Comment by fracpete** [comment]
Now works with 3.7.13 (requires 3.7.13 or later).
